apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: lijkal/udagram-api-feed:v10
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: "200Mi"
            requests:
              cpu: 200m
              memory: "100Mi"       
          envFrom:
            - configMapRef:
                    name: env-configmap
            - secretRef:
                    name: env-secret
            
          volumeMounts:
            - mountPath: "/root/.aws/"
              name: aws-secret
      volumes:
        - name: aws-secret
          configMap:
            name: aws-secret