apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: frontend
  template:
    metadata:
      labels: 
        app: frontend
    spec:
      containers:
        - name: frontend
          image: abdi123/udagram-frontend:v10
          ports:
            - containerPort: 80
        # resources:
        #   limits:
        #     cpu: 200m
        #   requests:
        #     cpu: 500m



